// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WallyBallBackend.Infrastructure.Persistence.SqlServer;

#nullable disable

namespace WallyBallBackend.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609212109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.AuditoriaResultado", b =>
                {
                    b.Property<int>("IdAuditoriaResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoriaResultado"));

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdEquipoGanadorAnterior")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipoGanadorNuevo")
                        .HasColumnType("int");

                    b.Property<int>("IdPartido")
                        .HasColumnType("int");

                    b.Property<int>("IdResultado")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SetsLocalAnterior")
                        .HasColumnType("int");

                    b.Property<int>("SetsLocalNuevo")
                        .HasColumnType("int");

                    b.Property<int>("SetsVisitanteAnterior")
                        .HasColumnType("int");

                    b.Property<int>("SetsVisitanteNuevo")
                        .HasColumnType("int");

                    b.HasKey("IdAuditoriaResultado");

                    b.HasIndex("IdResultado");

                    b.ToTable("AuditoriaResultados", (string)null);
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Campeonato", b =>
                {
                    b.Property<int>("IdCampeonato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCampeonato"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdCampeonato");

                    b.ToTable("Campeonatos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Campeonatos_Estado", "Estado IN ('BORRADOR', 'ACTIVO', 'FINALIZADO', 'CANCELADO')");

                            t.HasCheckConstraint("CK_Campeonatos_Fechas", "FechaFin IS NULL OR FechaFin >= FechaInicio");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVA");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdCampeonato", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categorias_Campeonato_Nombre");

                    b.ToTable("Categorias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categorias_Estado", "Estado IN ('ACTIVA', 'INACTIVA')");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdEquipo");

                    b.HasIndex("IdCategoria", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Equipos_Categoria_Nombre");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Fase", b =>
                {
                    b.Property<int>("IdFase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFase"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdFase");

                    b.HasIndex("IdCategoria", "Orden")
                        .IsUnique()
                        .HasDatabaseName("UQ_Fases_Categoria_Orden");

                    b.ToTable("Fases", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fases_Estado", "Estado IN ('PENDIENTE', 'ACTIVA', 'FINALIZADA', 'CANCELADA')");

                            t.HasCheckConstraint("CK_Fases_Tipo", "Tipo IN ('ROUND_ROBIN', 'ELIMINATORIA')");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.InscripcionEquipoJugador", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("IdJugador");

                    b.HasIndex("IdEquipo", "IdJugador")
                        .IsUnique()
                        .HasDatabaseName("UQ_Inscripciones_Equipo_Jugador");

                    b.ToTable("InscripcionesEquipoJugador", null, t =>
                        {
                            t.HasCheckConstraint("CK_Inscripciones_Estado", "Estado IN ('ACTIVO', 'RETIRADO')");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Jornada", b =>
                {
                    b.Property<int>("IdJornada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJornada"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PROGRAMADA");

                    b.Property<DateOnly?>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<int>("IdFase")
                        .HasColumnType("int");

                    b.Property<int>("NumeroJornada")
                        .HasColumnType("int");

                    b.HasKey("IdJornada");

                    b.HasIndex("IdFase", "NumeroJornada")
                        .IsUnique()
                        .HasDatabaseName("UQ_Jornadas_Fase_Numero");

                    b.ToTable("Jornadas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Jornadas_Estado", "Estado IN ('PROGRAMADA', 'FINALIZADA', 'CANCELADA')");

                            t.HasCheckConstraint("CK_Jornadas_Numero", "NumeroJornada > 0");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Jugador", b =>
                {
                    b.Property<int>("IdJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJugador"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdJugador");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasDatabaseName("UQ_Jugadores_Cedula");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("UQ_Jugadores_IdUsuario")
                        .HasFilter("[IdUsuario] IS NOT NULL");

                    b.ToTable("Jugadores", (string)null);
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Partido", b =>
                {
                    b.Property<int>("IdPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartido"));

                    b.Property<int>("EquipoMayor")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CASE WHEN IdEquipoLocal > IdEquipoVisitante THEN IdEquipoLocal ELSE IdEquipoVisitante END", true);

                    b.Property<int>("EquipoMenor")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CASE WHEN IdEquipoLocal < IdEquipoVisitante THEN IdEquipoLocal ELSE IdEquipoVisitante END", true);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PROGRAMADO");

                    b.Property<DateTime?>("FechaHoraProgramada")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipoLocal")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipoVisitante")
                        .HasColumnType("int");

                    b.Property<int>("IdFase")
                        .HasColumnType("int");

                    b.Property<int>("IdJornada")
                        .HasColumnType("int");

                    b.HasKey("IdPartido");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEquipoLocal");

                    b.HasIndex("IdEquipoVisitante");

                    b.HasIndex("IdJornada");

                    b.HasIndex("IdFase", "EquipoMenor", "EquipoMayor")
                        .IsUnique()
                        .HasDatabaseName("UQ_Partidos_Fase_Enfrentamiento");

                    b.HasIndex("IdFase", "IdEquipoLocal", "IdEquipoVisitante");

                    b.ToTable("Partidos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Partidos_EquiposDiferentes", "IdEquipoLocal <> IdEquipoVisitante");

                            t.HasCheckConstraint("CK_Partidos_Estado", "Estado IN ('PROGRAMADO', 'REPROGRAMADO', 'FINALIZADO', 'CANCELADO')");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.ReprogramacionPartido", b =>
                {
                    b.Property<int>("IdReprogramacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReprogramacion"));

                    b.Property<DateTime?>("FechaHoraAnterior")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraNueva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdPartido")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdReprogramacion");

                    b.HasIndex("IdPartido");

                    b.ToTable("ReprogramacionesPartido", (string)null);
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResultado"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdEquipoGanador")
                        .HasColumnType("int");

                    b.Property<int>("IdPartido")
                        .HasColumnType("int");

                    b.Property<int>("SetsLocal")
                        .HasColumnType("int");

                    b.Property<int>("SetsVisitante")
                        .HasColumnType("int");

                    b.HasKey("IdResultado");

                    b.HasIndex("IdEquipoGanador");

                    b.HasIndex("IdPartido")
                        .IsUnique()
                        .HasDatabaseName("UQ_Resultados_Partido");

                    b.ToTable("Resultados", null, t =>
                        {
                            t.HasCheckConstraint("CK_Resultados_NoEmpate", "SetsLocal <> SetsVisitante");

                            t.HasCheckConstraint("CK_Resultados_Sets", "SetsLocal >= 0 AND SetsVisitante >= 0");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.ResultadoSet", b =>
                {
                    b.Property<int>("IdResultadoSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResultadoSet"));

                    b.Property<int>("IdResultado")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSet")
                        .HasColumnType("int");

                    b.Property<int>("PuntosLocal")
                        .HasColumnType("int");

                    b.Property<int>("PuntosVisitante")
                        .HasColumnType("int");

                    b.HasKey("IdResultadoSet");

                    b.HasIndex("IdResultado", "NumeroSet")
                        .IsUnique()
                        .HasDatabaseName("UQ_ResultadoSets_Resultado_NumeroSet");

                    b.ToTable("ResultadoSets", null, t =>
                        {
                            t.HasCheckConstraint("CK_ResultadoSets_NoEmpate", "PuntosLocal <> PuntosVisitante");

                            t.HasCheckConstraint("CK_ResultadoSets_NumeroSet", "NumeroSet > 0");

                            t.HasCheckConstraint("CK_ResultadoSets_Puntos", "PuntosLocal >= 0 AND PuntosVisitante >= 0");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Nombre");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Activo = true,
                            Descripcion = "Usuario encargado de administrar campeonatos, categorias, equipos, jugadores, fixture, resultados y posiciones.",
                            Nombre = "ORGANIZADOR"
                        },
                        new
                        {
                            IdRol = 2,
                            Activo = true,
                            Descripcion = "Usuario que puede consultar fixture, resultados, posiciones e informacion de su equipo.",
                            Nombre = "JUGADOR"
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.TablaPosicion", b =>
                {
                    b.Property<int>("IdPosicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPosicion"));

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Ganados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int>("PartidosJugados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Perdidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Puntos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PuntosContra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PuntosFavor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SetsContra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SetsFavor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdPosicion");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdCategoria", "IdEquipo")
                        .IsUnique()
                        .HasDatabaseName("UQ_TablaPosiciones_Categoria_Equipo");

                    b.ToTable("TablaPosiciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_TablaPosiciones_Valores", "PartidosJugados >= 0 AND Ganados >= 0 AND Perdidos >= 0 AND SetsFavor >= 0 AND SetsContra >= 0 AND PuntosFavor >= 0 AND PuntosContra >= 0 AND Puntos >= 0");
                        });
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuarios_Email");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioRol");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario", "IdRol")
                        .IsUnique()
                        .HasDatabaseName("UQ_UsuarioRol_Usuario_Rol");

                    b.ToTable("UsuarioRol", (string)null);
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.AuditoriaResultado", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Resultado", "Resultado")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdResultado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Campeonato", "Campeonato")
                        .WithMany("Categorias")
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Equipo", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Equipos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Fase", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Fases")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.InscripcionEquipoJugador", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Equipo", "Equipo")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WallyBallBackend.Domain.Entities.Jugador", "Jugador")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdJugador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Jornada", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Fase", "Fase")
                        .WithMany("Jornadas")
                        .HasForeignKey("IdFase")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fase");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Jugador", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Jugador")
                        .HasForeignKey("WallyBallBackend.Domain.Entities.Jugador", "IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Partido", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Partidos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WallyBallBackend.Domain.Entities.Equipo", "EquipoLocal")
                        .WithMany("PartidosComoLocal")
                        .HasForeignKey("IdEquipoLocal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WallyBallBackend.Domain.Entities.Equipo", "EquipoVisitante")
                        .WithMany("PartidosComoVisitante")
                        .HasForeignKey("IdEquipoVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WallyBallBackend.Domain.Entities.Fase", "Fase")
                        .WithMany("Partidos")
                        .HasForeignKey("IdFase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WallyBallBackend.Domain.Entities.Jornada", "Jornada")
                        .WithMany("Partidos")
                        .HasForeignKey("IdJornada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Fase");

                    b.Navigation("Jornada");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.ReprogramacionPartido", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Partido", "Partido")
                        .WithMany("Reprogramaciones")
                        .HasForeignKey("IdPartido")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Resultado", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Equipo", "EquipoGanador")
                        .WithMany("ResultadosGanados")
                        .HasForeignKey("IdEquipoGanador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WallyBallBackend.Domain.Entities.Partido", "Partido")
                        .WithOne("Resultado")
                        .HasForeignKey("WallyBallBackend.Domain.Entities.Resultado", "IdPartido")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EquipoGanador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.ResultadoSet", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Resultado", "Resultado")
                        .WithMany("Sets")
                        .HasForeignKey("IdResultado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.TablaPosicion", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Categoria", "Categoria")
                        .WithMany("TablaPosiciones")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WallyBallBackend.Domain.Entities.Equipo", "Equipo")
                        .WithMany("TablaPosiciones")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("WallyBallBackend.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WallyBallBackend.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Campeonato", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Fases");

                    b.Navigation("Partidos");

                    b.Navigation("TablaPosiciones");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("PartidosComoLocal");

                    b.Navigation("PartidosComoVisitante");

                    b.Navigation("ResultadosGanados");

                    b.Navigation("TablaPosiciones");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Fase", b =>
                {
                    b.Navigation("Jornadas");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Jornada", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Jugador", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Reprogramaciones");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Resultado", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("WallyBallBackend.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Jugador");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
