@IdentidadService_HostAddress = http://localhost:5097
@AccessToken = reemplazar-con-token
@RefreshToken = reemplazar-con-refresh-token

POST {{IdentidadService_HostAddress}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "jugador@example.com",
  "password": "Password123!",
  "nombreCompleto": "Organizador Demo"
}

###

POST {{IdentidadService_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "jugador@example.com",
  "password": "Password123!"
}

###

POST {{IdentidadService_HostAddress}}/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{RefreshToken}}"
}

###

GET {{IdentidadService_HostAddress}}/api/v1/auth/me
Authorization: Bearer {{AccessToken}}
Accept: application/json

###

POST {{IdentidadService_HostAddress}}/api/v1/auth/change-password
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "currentPassword": "Password123!",
  "newPassword": "NewPassword123!"
}

###

POST {{IdentidadService_HostAddress}}/api/v1/auth/logout
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "refreshToken": "{{RefreshToken}}"
}

###

GET {{IdentidadService_HostAddress}}/api/v1/gestion/roles
Authorization: Bearer {{AccessToken}}
Accept: application/json

###

GET {{IdentidadService_HostAddress}}/api/v1/gestion/roles/1
Authorization: Bearer {{AccessToken}}
Accept: application/json

###

GET {{IdentidadService_HostAddress}}/api/v1/gestion/usuarios
Authorization: Bearer {{AccessToken}}
Accept: application/json

###

GET {{IdentidadService_HostAddress}}/api/v1/gestion/usuarios/1
Authorization: Bearer {{AccessToken}}
Accept: application/json

###
